LNCDCDSS/LNCDCDSS/Controllers/EnterPatInforController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LNCDCDSS.Models;
using System.Text.RegularExpressions;
using LNCDCDSS.Filters;
namespace LNCDCDSS.Controllers
{
    public class EnterPatInforController : Controller
    {
        VisitRecordOperation visitop = new VisitRecordOperation();
        
        //
        // GET: /EnterPatInfor/
        [AuthorizeActionFilter]
        public ActionResult Index()
        {
            return View();
           
        }
        [HttpPost]
        public ActionResult Index(PatBasicInfor pat)
        {
           
            PatOperation pto = new PatOperation();
            string HID = Request.Form["住院号"];
            string PID = Request.Form["门诊号"];
            if (string.IsNullOrEmpty(pat.Name) || string.IsNullOrEmpty(pat.Sex) || string.IsNullOrEmpty(pat.Age) || string.IsNullOrEmpty(pat.Education) || string.IsNullOrEmpty(pat.Phone) || string.IsNullOrEmpty(pat.FamilyMember) || string.IsNullOrEmpty(pat.ChiefDoctor))
            {
                ModelState.AddModelError("", "输入项不能为空");
            }
            else
            {
                Regex reg = new Regex("^[0-9]+$");
                Match ma1 = reg.Match(pat.Age);
                Match ma2 = reg.Match(pat.Phone);
                if (ma1.Success && ma2.Success)
                {
                }
                else
                {
                    ModelState.AddModelError("", "手机和年龄必须为数字");
                }


            }
            if (ModelState.IsValid)
            {
                
                    string user;

                    user = HttpContext.Request.Cookies["username"].Value.ToString();
              

                pto.InsertPat(pat, HID, PID,user);
                return RedirectToAction("Index", "Diagnosis", new { ID = pat.Id });
            }
            else
            {
                return View();
            }
            //   return Redirect("/Diagnosis/Index/"+pat.Id);


        }

        public ActionResult Query()
        {
            string user= HttpContext.Request.Cookies["username"].Value.ToString();
            string patname = Request["name"];
            string patsex = Request["sex"];
            string date = Request["date"];
            string diagnosisresult = Request["Diagnosis"];
            List<string> query = new List<string>();
            query.Add(patname);
            query.Add(patsex);
            query.Add(date);
            query.Add(diagnosisresult);
            query.Add(user);
            List<PatBasicInfor> pts = visitop.GetPat(query);

            //  return Json(pts, JsonRequestBehavior.AllowGet);
            return PartialView("PatList", pts);
        }
        [OutputCache(Location = System.Web.UI.OutputCacheLocation.None)]
        public ActionResult ViewRecord(string ID)
        {
            string t = ID;
            List<VisitRecord> vrecord = visitop.GetVistRecord(t);
         
              this.TempData["PatID"] = ID;
            this.ViewBag.patId = ID;
            return View(vrecord);
           
            
           
        }

        public ActionResult DetailView(int ID)
        {
            List<string> text = visitop.GetVisitContent(ID.ToString());
            DetaiInfor a = new DetaiInfor() { Name = "TestResult", Contetntext = text[0] };
            DetaiInfor b = new DetaiInfor() { Name = "Record", Contetntext = text[1] };
            DetaiInfor c = new DetaiInfor() { Name = "Diagnosis", Contetntext = text[2] };

            List<DetaiInfor> list = new List<DetaiInfor>();
            DetaiInfor id = new DetaiInfor() { Name = "ID", Contetntext = ID.ToString() };
            list.Add(a);
            list.Add(b);
            list.Add(c);
            this.TempData["recordID"] = ID.ToString();
            return Json(list, JsonRequestBehavior.AllowGet);

        }
        public class DetaiInfor
        {
            public string Name { set; get; }
            public string Contetntext { set; get; }
        }

        public ActionResult GoToDiagnosis(string ID)
        {
            visitop.AddNewRecord(ID);
            return RedirectToAction("Index", "Diagnosis", new { ID = ID });
        }
        public ActionResult ContinueDiagnosis(string ID)
        {
            string identity = ID+"%";
            
           identity =identity+ this.TempData["recordID"].ToString();
           return RedirectToAction("VisitContinue", "Diagnosis", new { identity = identity });
        }
        public ActionResult DeleteRecord(string ID)
        {

            // string jsonStr = Request.Params["postjson"];
            //  string PatID = this.TempData["PatID"].ToString();
            string PatID = ID;
            string RecordID = this.TempData["recordID"].ToString();
            try
            {
                visitop.DeleteRecord(PatID, RecordID);
            }
            catch (Exception e)
            {
                return this.Json(new { OK = false, Message = "删除失败" });
            }

            return this.Json(new { OK = true, Message = RecordID });
        }
    }
}

LNCDCDSS/LNCDCDSS/Views/EnterPatInfor/Index.cshtml
@model LNCDCDSS.Models.PatBasicInfor
@{
    ViewBag.Title = "GetPatient";
    Layout = "~/Views/Shared/PatLayout.cshtml";
}
@{
    var items = new SelectList(new[]
        { 
           new SelectListItem {Text = "", Value = ""},
            new SelectListItem {Text = "男", Value = "男"},
            new SelectListItem {Text = "女", Value = "女"},
        }, "Text", "Value");
}
@{
    var diagnosis = new SelectList(new[]
        {  new SelectListItem {Text = "", Value = ""},
            new SelectListItem {Text = "正常", Value = "正常"},
            new SelectListItem {Text = "MCI", Value = "MCI"},
             new SelectListItem {Text = "AD", Value = "AD"},
        }, "Text", "Value");
}
@{
    var education = new SelectList(new[]
        {  new SelectListItem {Text = "", Value = ""},
            new SelectListItem {Text = "1", Value = "文盲"},
            new SelectListItem {Text = "2", Value = "小学"},
             new SelectListItem {Text = "3", Value = "初中"}, 
          new SelectListItem {Text = "4", Value = "高中/中专"},
             new SelectListItem {Text = "5", Value = "大专/大学及以上"},
        }, "Text", "Value");
}
<div id="content">
    <div id="query">
        @using (Ajax.BeginForm("Query", new AjaxOptions { UpdateTargetId = "List", HttpMethod = "POST", InsertionMode = InsertionMode.Replace, OnSuccess = "ListPage" }))
        {
            <h2 class="title">
                查询病人</h2>
            <ul>
                <li><span>姓名</span>
                    @Html.TextBox("name")
                </li>
                <li><span>性别</span>
                    @Html.DropDownList("sex", @items)
                </li>
                <li><span>就诊日期</span><input type="text" name="date" id="date" />
                </li>
                <li><span>诊断结论</span> @Html.DropDownList("Diagnosis", @diagnosis)
                </li>
            </ul>
         
            <p>
                <input type="submit" value="查询病人" /></p>
        
        }
    </div>
    <div id="entry">
        <h2 class="title">
            新病人注册</h2>
        <div id="label">
            @using (Html.BeginForm("Index"))
            {
                <ul>
                    <li><span>门诊号</span><input type="text" name="门诊号" /></li>
                    <li><span>住院号</span><input type="text" name="住院号" /></li>
                    <li><span>姓名</span>@Html.EditorFor(model => model.Name)</li>
                    <li><span>性别</span>@Html.DropDownListFor(model => model.Sex, @items) </li>
                    <li><span>年龄</span> @Html.EditorFor(model => model.Age)</li>
                    <li><span>教育水平</span>@Html.DropDownListFor(model => model.Education, @education)
                    </li>
                    <li><span>职业</span>@Html.EditorFor(model => model.Job) </li>
                    <li><span>手机</span>@Html.EditorFor(model => model.Phone)</li>
                    <li><span>家属</span> @Html.EditorFor(model => model.FamilyMember)</li>
                    <li><span>主治医师</span>@Html.EditorFor(model => model.ChiefDoctor) </li>
                </ul>
            
                <p>
                    <input type="submit" value="注册新患者" /></p>
            
            }
        </div>
        <div>
            <span class="error" id="login_msg">@Html.ValidationSummary()</span></div>
    </div>
</div>
<div id="sidebar">
    <div id="List">
        <h2>
            病人列表</h2>
    </div>
     <div class="pagination">
        <a href="#" class="first" data-action="first">&laquo;</a> <a href="#" class="previous"
            data-action="previous">&lsaquo;</a>
        <input type="text" readonly="readonly" data-max-page="40" />
        <a href="#" class="next" data-action="next">&rsaquo;</a> <a href="#" class="last"
            data-action="last">&raquo;</a>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $(".pagination").hide();
        $("#date").Zebra_DatePicker();
    });
    function ListPage() {
        $(".page").find("li").hide();
        $(".pagination").show();
        $(".page li:lt(12)").addClass("current").show();
        var num = Math.ceil($(".page li").length / 12);
        $('.pagination').jqPagination({
            max_page: num,
            paged: function (page) {
                $(".current").hide();
                var start = (page - 1) * 12;
                for (var i = 0; i < 12; i++) {

                    $(".page li:eq(" + start + ")").addClass("current").show();
                    start = start + 1;
                }
                // do something with the page variable

            }
        })
    }
   
</script>

LNCDCDSS/LNCDCDSS/Views/EnterPatInfor/ViewRecord.cshtml
@{
    ViewBag.Title = "ViewRecord";
    Layout = "~/Views/Shared/PatLayout.cshtml";
     
}
@model List<LNCDCDSS.Models.VisitRecord>
<div id="content">
    <div id="ViewContent">
        <h2 class="title">
            认知检查</h2>
        <div id="TestResult">
            <table id="test" >
                <tr>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                </tr>
            </table>
        </div>
        <h2 class="title">
            主诉</h2>
        <div id="RecordNote">
         <div id="Record"> </div>
        </div>
        <h2 class="title">
            诊断</h2>
        <div id="DiagnosisResult">
        <div id="Diagnosis"> </div>
        </div>
        <div id="continue" class="button">
            <a>继续问诊</a>
        </div>
        <div id="diagnosis" class="button">
            <a>开始新问诊</a>
        </div>
        <div id="delete" class="button">
            <a>删除记录</a>
        </div>
      
    </div>
</div>
<div id="sidebar">
    <div id="List">
        <h2>
            记录列表</h2>
        <ul class="paging">
            @foreach (var item in Model)
            {
                <li><a href="#"  id="@item.Id">@item.VisitDate.Date.ToString("yyyy-MM-dd")</a> </li>
            }
        </ul>

          
    </div>
    <div class="pagination">
        <a href="#" class="first" data-action="first">&laquo;</a> <a href="#" class="previous"
            data-action="previous">&lsaquo;</a>
        <input type="text" readonly="readonly" data-max-page="40" />
        <a href="#" class="next" data-action="next">&rsaquo;</a> <a href="#" class="last"
            data-action="last">&raquo;</a>
    </div>
    <div id="return" class="button">
            @Html.ActionLink("返回查询", "index")
        </div>
</div>
<script type="text/javascript">
    $(function () {

        $(" li  a").click(function () {

            var recordToView = $(this).attr("id");

            if (recordToView != '') {

                // Perform the ajax post
                $.ajax({
                    url: '@Url.Action("DetailView", "EnterPatInfor")',
                    type: "POST",
                    data: { id: recordToView },
                    success: function (data) {
                        // Successful requests get here
                        // Update the page elements
                        var resultlist = data[0].Contetntext.split(";");
                        var datatable = document.getElementById("test");

                        for (var count = 0; count < 5; count++) {
                            var i = Math.floor(count / 3);
                            var j = count % 3;
                            datatable.rows[i].cells[j].innerText = resultlist[count];
                        }
                        for (var ncount = count; ncount < 16; ncount++) {
                            var k = ncount + 1;
                            var i = Math.floor(k / 3);
                            var j = k % 3;
                            datatable.rows[i].cells[j].innerText = resultlist[ncount];

                        }

                        for (var n = 1; n < data.length; n++) {
                            $("#" + data[n].Name).html(data[n].Contetntext);
                        }
                        $(".CurrentView").parent().css("background-color", "#B9DCF2");
                        $(".CurrentView").removeClass("CurrentView");
                        $('#' + recordToView).addClass("CurrentView");
                        $(".CurrentView").parent().css("background-color", "#D3E7F2");
                        $("#delete").show();
                        $("#continue").show();
                        $("#ViewContent").show();
                    },
                    error: function (jqXhr, textStatus, errorThrown) {
                        alert("Error '" + jqXhr.status + "' (textStatus: '" + textStatus + "', errorThrown: '" + errorThrown + "')");
                    }
                });
            }
        })

    });

    $(function () {
        $("#diagnosis").click(function () {
            window.location.href = '@Url.Action("GoToDiagnosis", "EnterPatInfor", new { id = ViewBag.patId }, null)';
        })

    });
    $(function () {
        $("#continue").click(function () {
            window.location.href = '@Url.Action("ContinueDiagnosis", "EnterPatInfor", new { id = ViewBag.patId }, null)';
        })

    });
        $(function () {
        $("#delete").click(function () {
            var pid = '@ViewBag.patId';
            $.ajax({
                url: '@Url.Action("DeleteRecord", "EnterPatInfor")',
                type: "POST",
                data: { id: pid },

                success: function (data) {
                    if (data.OK) {
                        $('#' + data.Message).parent().remove();
                        $("#ViewContent").hide();
                    }
                    else {
                        alert("删除失败");

                    }

                },
                error: function (jqXhr, textStatus, errorThrown) {
                    alert("Error '" + jqXhr.status + "' (textStatus: '" + textStatus + "', errorThrown: '" + errorThrown + "')");
                }
            });

        })
    });
    $(document).ready(function () {
        $("#delete").hide();
        $("#continue").hide();
        $(".paging").find("li").hide();
        $(".paging li:lt(12)").addClass("current").show();
        var num = Math.ceil($(".paging li").length / 12);
        $('.pagination').jqPagination({
            max_page: num,
            paged: function (page) {
                $(".current").hide();
                var start = (page - 1) * 12;
                for (var i = 0; i < 12; i++) {

                    $(".paging li:eq(" + start + ")").addClass("current").show();
                    start = start + 1;
                }
                // do something with the page variable

            }
        })
    });

</script>